version: '3'

services:
  ghost:
    image: ghost:latest
    environment:
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
      url: http://localhost:8080
    ports:
      - '2368:2368'
    volumes:
      - ./ghost-data:/var/lib/ghost/content
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '8080:8080'
    depends_on:
      - ghost
    restart: always
