version: '3'

services:
  ghost:
    image: ghost:latest
    environment:
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
    ports:
      - '2368:2368'
    volumes:
      - ./ghost-data:/var/lib/ghost/content
    restart: always
